export const stripHonorific = (name) => name.replace(/^(Mr\.|Ms\.)\s*/i, '').trim()

export const EMPLOYEE_DIRECTORY = [
  { empId: '2063023', name: stripHonorific('Ms. Jasmina Kamani') },
  { empId: '2342284', name: stripHonorific('Mr. Kamalakar L Naik') },
  { empId: '2824875', name: stripHonorific('Ms. Arya Ajay') },
  { empId: '1249596', name: stripHonorific('Mr. Vikash Guria') },
  { empId: '2764087', name: stripHonorific('Mr. Mukesh Kumar Singh') },
  { empId: '1072994', name: stripHonorific('Ms. Ramyakrishna Bondalapati') },
  { empId: '2405942', name: stripHonorific('Mr. Padmakumar Manikyam') },
  { empId: '892664', name: stripHonorific('Mr. Vignesh Subramanian') },
  { empId: '2713033', name: stripHonorific('Mr. Suman Saroj Khuntia') },
  { empId: '329634', name: stripHonorific('Mr. Kamlesh Debnath') },
  { empId: '2764880', name: stripHonorific('Mr. Viresh Kumar') },
  { empId: '2467137', name: stripHonorific('Ms. Arulmari K') },
  { empId: '2295573', name: stripHonorific('Mr. Battula Venkata Jagadesh Chowdary') },
  { empId: '1929610', name: stripHonorific('Mr. Aditya Katare') },
  { empId: '1027345', name: stripHonorific('Mr. Sudeep Kumar') },
  { empId: '1507312', name: stripHonorific('Mr. Shankar Alagarsamy') },
  { empId: '2841284', name: stripHonorific('Mr. Sumit Verma') },
  { empId: '204189', name: stripHonorific('Ms. Uma Maheswari V') },
  { empId: '2727718', name: stripHonorific('Ms. M Aarthy') },
  { empId: '2158275', name: stripHonorific('Ms. Reethika R') },
  { empId: '2519141', name: stripHonorific('Mr. Selva Eswar S') },
  { empId: '2798059', name: stripHonorific('Ms. Nandani Moreshwar Deshbhratar') },
  { empId: '2424221', name: stripHonorific('Mr. Janmejay Shanti') },
  { empId: '495827', name: stripHonorific('Ms. Ramyalakshmi K') },
  { empId: '2729968', name: stripHonorific('Ms. Rajya Lakshmi Kuchipudi') },
  { empId: '2622563', name: stripHonorific('Ms. Satya Nikitha Kattuboina') },
  { empId: '2058995', name: stripHonorific('Ms. Supraja Medam') },
  { empId: '2563108', name: stripHonorific('Mr. Nithish Kumar') },
  { empId: '2732095', name: stripHonorific('Mr. Yashaswi Sai Veedhula') },
  { empId: '2732444', name: stripHonorific('Mr. Sarath Chandra Janapati') },
  { empId: '2123111', name: stripHonorific('Ms. Chinmayi Naga Paranandi') },
  { empId: '2728505', name: stripHonorific('Mr. Eswar Sai Charan Kunireddy') },
  { empId: '2444819', name: stripHonorific('Mr. Beldi Yogesh') },
  { empId: '2363338', name: stripHonorific('Mr. Rakesh Konduru') },
  { empId: '1749039', name: stripHonorific('Mr. Kandlakunta Nithin') },
  { empId: '516081', name: stripHonorific('Mr. Ajaykumar B') },
  { empId: '314791', name: stripHonorific('Mr. Karthik B S') },
  { empId: '2287730', name: stripHonorific('Mr. Aadhavan S') },
  { empId: '1627664', name: stripHonorific('Ms. Tamilselvi B') },
  { empId: '2343411', name: stripHonorific('Mr. Bhagirathsinh R Rathod') },
  { empId: '2800588', name: stripHonorific('Mr. Karthik Kathiresan') },
  { empId: '2761452', name: stripHonorific('Ms. Laxmi A Hosamani') },
  { empId: '2461315', name: stripHonorific('Ms. Pooja Singh') },
  { empId: '2718798', name: stripHonorific('Mr. Solanki Bhavik Rajeshbhai') },
  { empId: '1857621', name: stripHonorific('Mr. Jeet Rajkumar Talreja') },
  { empId: '2705406', name: stripHonorific('Mr. Deepak Kumar') },
  { empId: '2212464', name: stripHonorific('Ms. Pooja Kalaje') },
  { empId: '2740449', name: stripHonorific('Mr. Avinash M') },
  { empId: '1571998', name: stripHonorific('Mr. Amit Jethabhai Khunti') },
  { empId: '2894684', name: stripHonorific('Ms. Thakkar Chandni') },
  { empId: '1213620', name: stripHonorific('Mr. Abhishek Jain') },
  { empId: '2668881', name: stripHonorific('Ms. Anamika Patel') },
  { empId: '1452672', name: stripHonorific('Mr. Subhash Patel') },
  { empId: '2516095', name: stripHonorific('Mr. Pushpendra Jadon') },
  { empId: '2589842', name: stripHonorific('Mr. Akshat Shrivastava') },
  { empId: '2729523', name: stripHonorific('Mr. Niladri Ghoshal') },
  { empId: '2459242', name: stripHonorific('Mr. A. Panduranga Reddy') },
  { empId: '2911130', name: stripHonorific('Mr. Akbar Shaik') },
  { empId: '2731079', name: stripHonorific('Mr. Ashwin M Krishnan') },
  { empId: '1131502', name: stripHonorific('Mr. Rama R') },
  { empId: '2899557', name: stripHonorific('Mr. Jais Varghese Joseph') },
  { empId: '922852', name: stripHonorific('Mr. Atul Gupta') },
  { empId: '545605', name: stripHonorific('Ms. Suniti Jha') },
  { empId: '2350862', name: stripHonorific('Mr. Raguladhithya S K') },
  { empId: '2368302', name: stripHonorific('Ms. Anjani Vankam') },
  { empId: '2648371', name: stripHonorific('Mr. Kapil Nikhil Jani') },
  { empId: '2746082', name: stripHonorific('Ms. Vishnupriya Ravichandran') },
  { empId: '378826', name: stripHonorific('Mr. Aditya Jairam') },
  { empId: '2905086', name: stripHonorific('Ms. Chiruguri Sony') },
  { empId: '1612445', name: stripHonorific('Ms. Sravani Miriyala') },
  { empId: '243768', name: stripHonorific('Mr. Jaya Kishore Pattaswamy') },
  { empId: '2742974', name: stripHonorific('Mr. Hemanth Kumar Gurubelli') },
  { empId: '2796835', name: stripHonorific('Ms. Kamujula Samyuktha') },
  { empId: '1243626', name: stripHonorific('Mr. Sudhanshu Shrivastava') },
  { empId: '1462884', name: stripHonorific('Ms. Amulya Chandupatla') },
  { empId: '2454663', name: stripHonorific('Ms. Manoja Soumitri') },
  { empId: '366835', name: stripHonorific('Mr. Nagendra Damara') },
  { empId: '824820', name: stripHonorific('Mr. Meenatchi Sundaram') },
  { empId: '883521', name: stripHonorific('Ms. Smita Arun Pawar') },
  { empId: '2660063', name: stripHonorific('Ms. Hemalatha S') },
  { empId: '1120529', name: stripHonorific('Mr. Suranjan Dasgupta') },
  { empId: '2888824', name: stripHonorific('Mr. Hariharan P') },
  { empId: '2639922', name: stripHonorific('Mr. Yash Bansal') },
  { empId: '2838212', name: stripHonorific('Ms. Tanya Saxena') },
  { empId: '2840514', name: stripHonorific('Mr. Abhinay Soni') },
  { empId: '2156351', name: stripHonorific('Mr. Suganth Ajish Kumar L A') },
  { empId: '2175087', name: stripHonorific('Ms. Jyothika Gotthula') },
  { empId: '2261131', name: stripHonorific('Ms. Jasmine JS') },
  { empId: '271183', name: stripHonorific('Mr. Wilfred Rodrigues') },
  { empId: '866846', name: stripHonorific('Mr. Premkumar R') },
  { empId: '2765425', name: stripHonorific('Mr. Anil Kumar') },
  { empId: '1620614', name: stripHonorific('Mr. Rajasekhar C') },
  { empId: '2051516', name: stripHonorific('Ms. Sravanya Talathoti') },
  { empId: '2952612', name: stripHonorific('Ms. Azmeera Rajeswari') },
  { empId: '2402755', name: stripHonorific('Ms. Greeshma Rani Yarramsetty') },
  { empId: '2760595', name: stripHonorific('Ms. Soundariya S') },
  { empId: '1342730', name: stripHonorific('Ms. Nandini Kalyanasundharam') },
  { empId: '2398332', name: stripHonorific('Ms. Sowjanya Panidepu') },
  { empId: '2299252', name: stripHonorific('Mr. Jayachander Lakavath') },
  { empId: '1695303', name: stripHonorific('Mr. Bathula Nandeeswar') },
  { empId: '2495365', name: stripHonorific('Ms. Sandip Lakum') },
  { empId: '1506887', name: stripHonorific('Ms. Manasa Devi') },
  { empId: '2852968', name: stripHonorific('Ms. Abhinaya') },
  { empId: '2853124', name: stripHonorific('Mr. Vishal Singh Gurjar') },
  { empId: '2376935', name: stripHonorific('Ms. Jyothsna Lakshmi Garaga') },
  { empId: '2645443', name: stripHonorific('Mr. Ayush Sharma') },
  { empId: '2704664', name: stripHonorific('Ms. Yamini Prasanr Kumari Kesanakurthi') },
  { empId: '2084278', name: stripHonorific('Ms. Shefali Sinha') },
  { empId: '2715794', name: stripHonorific('Ms. Tejaswini Roopali Patil') },
  { empId: '1853896', name: stripHonorific('Ms. Rajni Mehra') },
  { empId: '2662769', name: stripHonorific('Ms. Jaichithra Bathiyappa') },
  { empId: '2042494', name: stripHonorific('Ms. Devata Rao Doddi') },
  { empId: '1232098', name: stripHonorific('Mr. Srinivas Chakravarth Gunturu') },
  { empId: '2570756', name: stripHonorific('Mr. Kiran Shankar Jadav') },
  { empId: '2742657', name: stripHonorific('Mr. Ravilisetty Dharma Teja') },
  { empId: '2715142', name: stripHonorific('Ms. Aarohi Shah') },
  { empId: '2400999', name: stripHonorific('Mr. Chetan Chouhan') },
  { empId: '2709258', name: stripHonorific('Mr. Naveen Kumar Reddy Ya') },
  { empId: '2051969', name: stripHonorific('Mr. Ankit Verma') },
  { empId: '2712874', name: stripHonorific('Mr. Umer Ali') },
  { empId: '1253821', name: stripHonorific('Mr. Shiv Tripathy') },
  { empId: '1635231', name: stripHonorific('Ms. Swathi Kethavarapu') },
  { empId: '2015338', name: stripHonorific('Mr. Ramu Nalluri') },
  { empId: '2148334', name: stripHonorific('Mr. Nagesh Kaku') },
  { empId: '271975', name: stripHonorific('Mr. Krishnamurari Mishra') },
  { empId: '2011359', name: stripHonorific('Mr. Ajin Velappan Leela') },
  { empId: '1636871', name: stripHonorific('Mr. Anil Vaghela') },
  { empId: '2259148', name: stripHonorific('Mr. Arun Saminathan') },
  { empId: '2716878', name: stripHonorific('Mr. Jaykumar Bera') },
  { empId: '731056', name: stripHonorific('Ms. Madhuri Bondada') },
  { empId: '1222429', name: stripHonorific('Mr. Suresh Kumar Manikireddy') },
  { empId: '469542', name: stripHonorific('Mr. Praveen Kumar Raghiphani') },
  { empId: '730106', name: stripHonorific('Ms. Leela Pravallika Alaparthi') },
  { empId: '1743591', name: stripHonorific('Mr. Tusharkumar Lad') },
  { empId: '1578020', name: stripHonorific('Mr. Agniva Bhattacharya') },
  { empId: '1715688', name: stripHonorific('Mr. Sureshbhai Vachhani') },
  { empId: '2705751', name: stripHonorific('Mr. Mahesh Lakshmanan') },
  { empId: '2449250', name: stripHonorific('Mr. Venkata Satya Aditya Koppisetti') },
  { empId: '2494886', name: stripHonorific('Mr. Anji Reddy Bijjam') },
  { empId: '314460', name: stripHonorific('Ms. Renu Raghavan Adathedath') },
  { empId: '2250622', name: stripHonorific('Ms. Brindha Sampath') },
  { empId: '317370', name: stripHonorific('Mr. Suresh S') },
  { empId: '2479649', name: stripHonorific('Mr. Isaac G') },
  { empId: '2333500', name: stripHonorific('Ms. Shajna Kamar') },
  { empId: '2374236', name: stripHonorific('Mr. Saharsh Naryani') },
  { empId: '2532136', name: stripHonorific('Mr. Irfan Ahmed') },
  { empId: '2847058', name: stripHonorific('Mr. Ajay Govindsingh Rajput') },
]

export const findDirectoryByName = (name) => {
  const normalized = stripHonorific(name).toLowerCase().trim()
  return EMPLOYEE_DIRECTORY.find((entry) => entry.name.toLowerCase() === normalized)
}

export const findDirectoryByEmpId = (empId) => {
  const normalized = `${empId || ''}`.trim()
  return EMPLOYEE_DIRECTORY.find((entry) => entry.empId === normalized)
}
